/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#ffb800",
        "secondary": "#5a4bda",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#1b1c17",
        "on-error-container": "#93000a",
        "error": "#ef4444",
        "surface-container-high": "#eef2ff",
        "surface-dim": "#cbd5e1",
        "on-secondary-fixed-variant": "#4338ca",
        "primary": "#5a4bda",
        "on-tertiary-fixed-variant": "#474742",
        "on-background": "#0f172a",
        "surface-container-low": "#f8fafc",
        "background": "#f4f6fb",
        "on-primary-fixed": "#1e1b4b",
        "surface-variant": "#e2e8f0",
        "primary-container": "#4538c6",
        "on-secondary-fixed": "#1e1b4b",
        "outline-variant": "#cbd5e1",
        "inverse-surface": "#1e293b",
        "inverse-on-surface": "#f8fafc",
        "on-secondary-container": "#0f172a",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffffff",
        "surface-tint": "#5a4bda",
        "primary-fixed": "#e0e7ff",
        "surface-bright": "#f4f6fb",
        "secondary-container": "#ffb800",
        "primary-fixed-dim": "#c7d2fe",
        "outline": "#64748b",
        "error-container": "#fee2e2",
        "surface": "#f4f6fb",
        "surface-container-highest": "#e2e8f0",
        "on-tertiary-container": "#94a3b8",
        "on-surface": "#0f172a",
        "on-primary-fixed-variant": "#3730a3",
        "tertiary-fixed-dim": "#cbd5e1",
        "surface-container": "#f1f5f9",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-container": "#1e293b",
        "tertiary-fixed": "#e2e8f0",
        "on-surface-variant": "#475569",
        "on-error": "#ffffff",
        "inverse-primary": "#c7d2fe",
        "secondary-fixed": "#fef08a",
        "tertiary": "#0f172a",
        "pw-blue": "#5a4bda",
        "pw-navy": "#0f172a",
        "pw-card": "#1e293b",
        "pw-gold": "#ffb800"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "16px",
        "stack-lg": "24px",
        "stack-sm": "8px",
        "container-margin": "20px",
        "stack-md": "16px"
      },
      fontFamily: {
        "display-lg-mobile": ["Quicksand"],
        "body-lg": ["Inter"],
        "display-lg": ["Quicksand"],
        "headline-md": ["Quicksand"],
        "body-md": ["Inter"],
        "title-lg": ["Quicksand"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "display-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms')
  ],
}
